services:
  web:
    build: .
    container_name: cgi-apache-app
    ports:
      - "8081:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./gadgets:/usr/share/
    depends_on:
      - php
    restart: always

  php:
    image: php:8.2-fpm
    container_name: my-php-fpm
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - ./gadgets:/usr/share/